version: "3.7"

services:

  backend:
    build:
      context: ./backend
    image: docker-learn__backend-image
    container_name: docker-learn__backend-container
    volumes:
      - ./backend/src:/usr/src/app
      - /usr/src/app/node_modules

  proxy:
    build:
      context: ./proxy
    image: docker-learn__proxy-image
    container_name: docker-learn__proxy-container
    volumes:
      - ./proxy/src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3031:3001
    links:
      - backend:back

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker-learn__frontend-image
    container_name: docker-learn__frontend-container
    volumes:
      - ./frontend/src:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: npm run start
