version: "3.7"

services:

  backend:
    build:
      dockerfile: prod.Dockerfile
    environment:
      - NODE_ENV=production
    restart: always
    entrypoint: npm run start

  proxy:
    build:
      dockerfile: prod.Dockerfile
    environment:
      - NODE_ENV=production
    restart: always
    entrypoint: npm run start

  frontend:
    environment:
      - NODE_ENV=production
