version: "3"

services:

  backend:
    environment:
      - NODE_ENV=production
    volumes:
      - /usr/src/app/node_modules
    restart: always
    entrypoint: npm run start

#  proxy:
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ./proxy/src:/usr/src/app
#    entrypoint: npm run watch
#
#  frontend:
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ./frontend/src:/usr/src/app
#    entrypoint: npm run watch
