version: "3.7"

services:

  backend:
    build:
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
    entrypoint: npm run watch

  proxy:
    build:
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
    entrypoint: npm run watch

  frontend:
    environment:
      - NODE_ENV=development
