version: "3"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: docker-learn__backend-image
    container_name: docker-learn__backend-container

#  proxy:
#    build:
#      context: ./proxy
#      dockerfile: Dockerfile
#    image: docker-learn__proxy-image
#    container_name: docker-learn__proxy-container
#    volumes:
#      - /usr/src/app/node_modules
#    ports:
#      - 3031:3001
#    entrypoint: npm run start
#    links:
#      - backend:back
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    image: docker-learn__frontend-image
#    container_name: docker-learn__frontend-container
#    volumes:
#      - /usr/src/app/node_modules
#    entrypoint: npm run start
